services:
  - type: web
    name: razavieh-masjid
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Razavieh.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Razavieh.settings
      - key: PYTHON_VERSION
        value: 3.12